# This file defines how the docker images are used in containers
# By default, the docker compose automatically creates a network specifically for this application stack

version: '3.9'
# define the list of containers (also referred as services)
services:
  api:
    # specifies the Dockerfile to build the image from
    build:
      context: ./packages
      dockerfile: ./api/Dockerfile
    ports:
      - 5555:5555
    volumes:
      # bind mount the ./src dir of the host OS into the /app dir inside container
      - ./api/src:/app/api/src
      - ./shared/src:/app/shared/src
    depends_on:
      - pg
      - redis
    networks:
      - default

  pg:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myUser
      - POSTGRES_PASSWORD=myPassword
      - POSTGRES_DB=metis
    networks:
      - default

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - default

  # localstack:
  #   image: localstack/localstack
  #   ports:
  #     - 4566:4566
  #   environment:
  #     - SERVICES=s3
  #     - DEFAULT_REGION=us-east-1
  #   volumes:
  #     - ./scripts/localstack:/docker-entrypoint-initaws.d/

networks:
  default:
    driver: bridge
