# This file defines how the docker images are used in containers
# By default, the docker compose automatically creates a network specifically for this application stack

version: "3.9"
# define the list of containers (called as services)
services:
  pg:
    container_name: metis-pg-test
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myUser
      - POSTGRES_PASSWORD=myPassword
      - POSTGRES_DB=myTestDatabase

  # redis:
  #   container_name: metis-redis-test
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
